### ISSUE TITLE
Erreur sur modification d'une WorkshopSession

### ISSUE THREAD

**Issue by sqlilabs** [sqlilabs/WorkshopManager#6]
La modification d'une workshopSession amène l'erreur: RollbackException: Error while committing the transaction

avec la stack trace:

[error] application - 

! @6de6jhmgg - Internal server error, for request [POST /workshops/planifier/9] ->

play.core.ActionInvoker$$anonfun$receive$1$$anon$1: Execution exception [[RollbackException: Error while committing the transaction]]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:134) [play_2.9.1.jar:2.0.3]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:115) [play_2.9.1.jar:2.0.3]
    at akka.actor.Actor$class.apply(Actor.scala:318) [akka-actor.jar:2.0.2]
    at play.core.ActionInvoker.apply(Invoker.scala:113) [play_2.9.1.jar:2.0.3]
    at akka.actor.ActorCell.invoke(ActorCell.scala:626) [akka-actor.jar:2.0.2]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:197) [akka-actor.jar:2.0.2]
Caused by: javax.persistence.RollbackException: Error while committing the transaction
    at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:92) ~[hibernate-entitymanager-4.1.6.Final.jar:4.1.6.Final]
    at play.db.jpa.JPA.withTransaction(JPA.java:110) ~[play_2.9.1.jar:2.0.3]
    at play.db.jpa.TransactionalAction.call(TransactionalAction.java:14) ~[play_2.9.1.jar:2.0.3]
    at play.core.j.JavaAction$class.apply(JavaAction.scala:74) ~[play_2.9.1.jar:2.0.3]
    at play.core.Router$HandlerInvoker$$anon$4$$anon$1.apply(Router.scala:1085) ~[play_2.9.1.jar:2.0.3]
    at play.core.ActionInvoker$$anonfun$receive$1$$anonfun$6.apply(Invoker.scala:126) ~[play_2.9.1.jar:2.0.3]
Caused by: java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing: models.Workshop.workshopSession -> models.WorkshopSession
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1374) ~[hibernate-entitymanager-4.1.6.Final.jar:4.1.6.Final]
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1300) ~[hibernate-entitymanager-4.1.6.Final.jar:4.1.6.Final]
    at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:80) ~[hibernate-entitymanager-4.1.6.Final.jar:4.1.6.Final]
    at play.db.jpa.JPA.withTransaction(JPA.java:110) ~[play_2.9.1.jar:2.0.3]
    at play.db.jpa.TransactionalAction.call(TransactionalAction.java:14) ~[play_2.9.1.jar:2.0.3]
    at play.core.j.JavaAction$class.apply(JavaAction.scala:74) ~[play_2.9.1.jar:2.0.3]
Caused by: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing: models.Workshop.workshopSession -> models.WorkshopSession
    at org.hibernate.engine.spi.CascadingAction$8.noCascade(CascadingAction.java:380) ~[hibernate-core-4.1.6.Final.jar:4.1.6.Final]
    at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:176) ~[hibernate-core-4.1.6.Final.jar:4.1.6.Final]
    at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:160) ~[hibernate-core-4.1.6.Final.jar:4.1.6.Final]
    at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:151) ~[hibernate-core-4.1.6.Final.jar:4.1.6.Final]
    at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:88) ~[hibernate-core-4.1.6.Final.jar:4.1.6.Final]
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51) ~[hibernate-core-4.1.6.Final.jar:4.1.6.Final]

---
- Bitbucket: https://bitbucket.org/sqlilabs/workshop-manager/issue/4
- Originally Reported By: [Yannick Chartois](http://bitbucket.org/ychartois)
- Originally Created At: 2013-02-25T09:43:51.967

**Comment by sqlilabs** [comment]
l'id de la précédente session n'était pas réaffectée...

---

Original Comment By: [Yannick Chartois](http://bitbucket.org/ychartois)
